# Generated by Django 3.2.5 on 2021-08-18 20:38

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examinor',
            fields=[
                ('examinor_username', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('examinor_password', models.CharField(max_length=128)),
                ('examinor_name', models.CharField(max_length=100)),
                ('examinor_id', models.IntegerField()),
                ('examinor_email', models.EmailField(max_length=254)),
                ('examinor_contact', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='thesis',
            fields=[
                ('Id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('time', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('field', models.CharField(max_length=100)),
                ('filepass', models.CharField(max_length=100)),
                ('feedack', models.FileField(upload_to='feedback')),
                ('file', models.FileField(upload_to='thesis')),
                ('assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.examinor')),
            ],
        ),
    ]
