# Generated by Django 3.2.5 on 2021-08-21 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210820_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='assigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.examinor'),
        ),
    ]
