# Generated by Django 3.2.5 on 2021-08-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_thesis_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='file',
            field=models.FileField(upload_to='THESI'),
        ),
    ]
